### ISSUE TITLE
Not all description info

### ISSUE THREAD

**Issue by Morb0** [timvandam/steam-inventory-stream#2]
Hey,
why you don't get all item data from `description` such as `tags`, `descriptions`, and some game-specific fields?

Can it just merge the remaining non-typed fields?
```javascript
const { currency, icon_url: iconUrl, tradable, /* ... */, marketable, ...other } = description
/* ... */
Object.assign(this, other)
```

I can create merge request if need.

**Comment by timvandam** [comment]
I didn’t do descriptions because they can use quite a bit of memory but since this is a stream anyway I suppose you can add it. 

I don’t do object.assign because camelcase :P

Thanks for the suggestion 👍

**Comment by timvandam** [comment]
I’m going to recreate this package with async generators soon so if you want you can also just wait for that. I’ll make sure it works there

**Comment by Morb0** [comment]
Fine, thx you for lib

P.S: It would be great if there were also typescript defs

**Comment by timvandam** [comment]
Yep typescript type defs will be in the async generator one

**Comment by timvandam** [comment]
https://www.npmjs.com/package/steam-inventory-iterator here it is
